### ISSUE TITLE
总是用一段时间就没有提示了

### ISSUE THREAD

**Issue by necan** [re-ovo/unocss-intellij#12]
总是用一段时间就没有提示了，然后 webstorm 报错，有时候需要重启 webstorm 才能解决，这次彻底挂了。
版本是 1.1.3，错误信息如下：

```
java.lang.RuntimeException: Unknown template shorthand: position
	at me.rerere.unocssintellij.UnocssService$getCompletion$response$1$1$invokeSuspend$$inlined$sendCommand$1.invoke(UnocssProcess.kt:132)
	at me.rerere.unocssintellij.UnocssService$getCompletion$response$1$1$invokeSuspend$$inlined$sendCommand$1.invoke(UnocssProcess.kt:129)
	at me.rerere.unocssintellij.UnocssProcess$1$1.invoke(UnocssProcess.kt:70)
	at me.rerere.unocssintellij.UnocssProcess$1$1.invoke(UnocssProcess.kt:58)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by re-ovo** [comment]
不确定为什么，建议等1.2.0更新，在审核了

**Comment by re-ovo** [comment]
更新了，试试看
