### ISSUE TITLE
版本1.2.1报错。

### ISSUE THREAD

**Issue by yanhao98** [re-ovo/unocss-intellij#16]
不知道是不是和我项目里的svg有关。

```

  Error while parsing SVG.
  
  com.fasterxml.aalto.WFCException: Duplicate attributes "width" (index 0), "width" (index 1)
at [row,col {unknown-source}]: [1,173]
at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
at com.fasterxml.aalto.in.Utf8Scanner.handleStartElement(Utf8Scanner.java:258)
at com.fasterxml.aalto.in.StreamScanner.nextFromProlog(StreamScanner.java:209)
at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:260)
at com.github.weisj.jsvg.parser.StaxSVGLoader.load(StaxSVGLoader.java:86)
at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:72)
at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:64)
at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:60)
at me.rerere.unocssintellij.marker.SVGIcon.<init>(UnoIcons.kt:29)
at me.rerere.unocssintellij.marker.UnocssLineMarkerProvider.getLineMarkerInfo(UnocssLineMarkerProvider.kt:40)
at me.rerere.unocssintellij.marker.UnocssHtmlLineMarkerProvider.getFromXmlAttributeValueToken(UnocssHtmlLineMarkerProvider.kt:36)
at me.rerere.unocssintellij.marker.UnocssHtmlLineMarkerProvider.doGetLineMarkerInfo(UnocssHtmlLineMarkerProvider.kt:19)
at me.rerere.unocssintellij.marker.UnocssJsLineMarkerProvider.doGetLineMarkerInfo(UnocssJsLineMarkerProvider.kt:16)
at me.rerere.unocssintellij.marker.UnocssLineMarkerProvider.getLineMarkerInfo(UnocssLineMarkerProvider.kt:17)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:107)
at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


```

**Comment by re-ovo** [comment]
用的什么图标

**Comment by yanhao98** [comment]
> 用的什么图标

自己导出的图标。

**Comment by yanhao98** [comment]
> > 用的什么图标
> 
> 自己导出的图标。

https://github.com/yanhao98/files/blob/main/uno-svg.zip

**Comment by re-ovo** [comment]
怎么配置的

**Comment by yanhao98** [comment]
> 怎么配置的

插件能正常使用。

```import {defineConfig, presetAttributify, presetIcons, presetUno, transformerVariantGroup} from 'unocss'
import presetRemToPx from '@unocss/preset-rem-to-px'
import {FileSystemIconLoader} from '@iconify/utils/lib/loader/node-loaders'
export default defineConfig({
  // By default, `.ts` and `.js` files are NOT extracted.
  // https://github.com/unocss/unocss/issues/2195
  safelist: ['i-icon:edit', 'i-icon:remove', 'i-icon:add-group'],
  rules: [['custom-rule', {color: 'red'}]],
  shortcuts: {
    'custom-shortcut': 'text-lg text-orange hover:text-teal',
  },
  presets: [
    presetUno({
      prefix: 'uno-',
    }),
    presetRemToPx({
      baseFontSize: 4,
    }),
    presetAttributify(),
    presetIcons({
      //  <div class="i-icon:pacman uno-text-(pink 36)" />
      collections: {
        icon: FileSystemIconLoader('./src/assets/uno-svg', (svg) => {
          return svg.replace(/#000000|#000/g, 'currentColor')
        }),
      },
      warn: true,
    }),
  ],
  transformers: [
    transformerVariantGroup(),
  ],
  /*content: {
    pipeline: {
    }
  }*/
}) ```

**Comment by yanhao98** [comment]
"@unocss/preset-rem-to-px": "^0.55.1",
    "@unocss/webpack": "^0.55.1",
    "unocss": "^0.55.1",

**Comment by yanhao98** [comment]
我这里也没能复现了。昨天是关了WS，再打开也会出现。
