### ISSUE TITLE
Why UnoCss Pluin always  show me  “Updating unocss config”  in Webstorm IDE  ??

### ISSUE THREAD

**Issue by lonesomeGoblin** [re-ovo/unocss-intellij#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Plugin Version: # 
IDE Version: #
Unocss Version(in package.json): #

**Unocss Config**:
(Share your uno.config.js/ts or vite config here)

**Comment by LuciferSama-AI** [comment]
It used nearly 200 processes

**Comment by re-ovo** [comment]
Please provide the specific operating environment, such as webstorm version, log, operating system, node version, configuration file, etc.

**Comment by LuciferSama-AI** [comment]
IDE:  Webstorm 2024.1.4   
node version:  nodejs 20.12.0
operating  environment: Ubuntu 24.04

**Comment by re-ovo** [comment]
log

**Comment by zhupeikang** [comment]
+1,也是在WSL2中出现的这个问题
开发环境版本跟@LuciferSama-AI一样
log ：java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:63)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:239)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:491)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:464)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:357)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at me.rerere.unocssintellij.UnocssProcess.<init>(UnocssProcess.kt:56)
	at me.rerere.unocssintellij.UnocssService.initProcess-IoAF18A(UnocssService.kt:157)
	at me.rerere.unocssintellij.UnocssService.getProcess(UnocssService.kt:113)
	at me.rerere.unocssintellij.UnocssService.resolveCss(UnocssService.kt:260)
	at me.rerere.unocssintellij.model.UnocssResolveMeta$resolveCss$1$1.invokeSuspend(UnocssResolveMeta.kt:30)
	at me.rerere.unocssintellij.model.UnocssResolveMeta$resolveCss$1$1.invoke(UnocssResolveMeta.kt)
	at me.rerere.unocssintellij.model.UnocssResolveMeta$resolveCss$1$1.invoke(UnocssResolveMeta.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
	at me.rerere.unocssintellij.model.UnocssResolveMeta$resolveCss$1.invokeSuspend(UnocssResolveMeta.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:132)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$5(context.kt:107)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:1022)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:105)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:75)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at me.rerere.unocssintellij.model.UnocssResolveMeta.resolveCss(UnocssResolveMeta.kt:29)
	at me.rerere.unocssintellij.marker.inlay.UnocssColorPreviewInlayHintsProvider$MyCollector.collect(UnocssColorPreviewInlayHintsProvider.kt:176)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:97)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$1(InlayHintsPass.kt:60)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:89)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by re-ovo** [comment]
插件什么版本 @zhupeikang

**Comment by zhupeikang** [comment]
> 插件什么版本 @zhupeikang

1.5.0

**Comment by re-ovo** [comment]
> > 插件什么版本 @zhupeikang
> 
> 1.5.0

用的WSL开发吗？

**Comment by zhupeikang** [comment]
> > > 插件什么版本 @zhupeikang
> > 
> > 
> > 1.5.0
> 
> 用的WSL开发吗？

是的

**Comment by re-ovo** [comment]
> > > > 插件什么版本 @zhupeikang
> > > 
> > > 
> > > 1.5.0
> > 
> > 
> > 用的WSL开发吗？
> 
> 是的

和这个issue有关
https://youtrack.jetbrains.com/issue/IDEA-347138

建议用本地开发，或者试试2024.2 EAP

**Comment by zhupeikang** [comment]
> > > > > 插件什么版本 @zhupeikang
> > > > 
> > > > 
> > > > 1.5.0
> > > 
> > > 
> > > 用的WSL开发吗？
> > 
> > 
> > 是的
> 
> 和这个issue有关 https://youtrack.jetbrains.com/issue/IDEA-347138
> 
> 建议用本地开发，或者试试2024.2 EAP

本地开发是没有这个问题的。我试试EAP版

**Comment by Gazoon007** [comment]
@re-ovo I still have this issue in my WSL2, I have updated it to 2042.2 and also run it as administrator
![image](https://github.com/user-attachments/assets/669c174a-0567-4123-a08d-047fcf13e973)

**Comment by Gazoon007** [comment]
> @re-ovo I still have this issue in my WSL2, I have updated it to 2042.2 and also run it as administrator

```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to flush the output stream: Process exited
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:555)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:573)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1007)
	at com.intellij.util.ConcurrencyUtil.manifestExceptionsIn(ConcurrencyUtil.java:277)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$24(DaemonCodeAnalyzerImpl.java:1222)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to flush the output stream: Process exited
	at java.base/java.util.concurrent.ForkJoinTask.completeExceptionally(ForkJoinTask.java:950)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:195)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.io.IOException: Failed to flush the output stream: Process exited
	at com.intellij.execution.ijent.IjentStdinOutputStream.flush(IjentStdinOutputStream.kt:36)
	at me.rerere.unocssintellij.UnocssService$resolveAnnotations$$inlined$sendCommand$1.invokeSuspend(UnocssProcess.kt:132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: com.intellij.platform.ijent.IjentChildProcess$SendStdinError$ProcessExited: Process exited
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcess.sendStdinWithConfirmation(GrpcIjentChildProcess.kt:154)
	at com.intellij.platform.ijent.impl.GrpcIjentChildProcess$sendStdinWithConfirmation$1.invokeSuspend(GrpcIjentChildProcess.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.execution.ijent.IjentStdinOutputStream.flush(IjentStdinOutputStream.kt:31)
	... 9 more
```
